#!/bin/bash

###
#
#            Name:  MAU_HowToCheck.sh
#     Description:  This EA for Jamf Pro Servers checks for the HowToCheck setting
#                   on a Mac with Office installed. Useful as a Smart Computer
#                   Group for scoping policies and configuration profiles.
#          Author:  Dr. Emily Kausalik (drkausalik@gmail.com)
#         Created:  2016-08-17
#
###

loggedInUser=$(python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");')

HowToCheck=$(defaults read /Users/$loggedInUser/Library/Preferences/com.microsoft.autoupdate2.plist HowToCheck)

if [ "$HowToCheck" ]; then
      echo "<result>$HowToCheck</result>"
else
      echo "<result>Not Installed</result>"
fi
