#!/bin/bash

###
#
#            Name:  MAU_HowToCheck.sh
#     Description:  This EA for Jamf Pro Servers checks for the HowToCheck setting
#                   on a Mac with Office installed. Useful as a Smart Computer
#                   Group for scoping policies and configuration profiles.
#          Author:  github.com/smashism
#         Created:  2016-08-17
#         Updated:  2022-01-29
#
###

loggedInUser=$( echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ { print $3 }' )

HowToCheck=$(defaults read /Users/$loggedInUser/Library/Preferences/com.microsoft.autoupdate2.plist HowToCheck)

if [ "$HowToCheck" ]; then
      echo "<result>$HowToCheck</result>"
else
      echo "<result>Not Installed</result>"
fi
